defaults:
  branches:
  - release-1.31
  repo-allowlist:
  - api
org: istio
repo: api
transforms:
- job-allowlist:
  - build_release-1.31
  - gencheck_release-1.31
  job-type:
  - presubmit
- job-allowlist:
  - build_release-1.31
  - gencheck_release-1.31
  job-type:
  - postsubmit
