org: istio
repo: proxy
support_release_branching: true

defaults:
  branches: [master]
  repo-allowlist: [proxy]
  modifier: master_priv

transforms:

# istio/proxy master test jobs(s) - presubmit(s)
- labels:
    preset-enable-netrc: "true"
  job-type: [presubmit]

# istio/proxy master arm build job - postsubmit
- env:
    GCS_BUILD_BUCKET: istio-build-private
  labels:
    preset-enable-netrc: "true"
  job-type: [postsubmit]
  job-allowlist: ["^release-arm64_proxy"]
  selector:
    testing: test-pool

# istio/proxy master x86 build job - postsubmit
- env:
    GCS_BUILD_BUCKET: istio-build-private
  labels:
    preset-enable-netrc: "true"
  job-type: [postsubmit]
  job-allowlist: ["^release_proxy"]
  selector:
    testing: build-pool
