---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: test-pods
  # Default service account that only has permissions to access the GCS bucket
  # for logging.
  name: prowjob-default-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: test-pods
  name: prow-deployer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: test-pods
  name: bots-deployer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: test-pods
  name: testgrid-updater
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: test-pods
  name: prowjob-bots-deployer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: test-pods
  # Service account that has permissions to push to gcr.io/istio-testing and gs://istio-build.
  name: prowjob-testing-write
