org: istio
repo: istio
support_release_branching: true

defaults:
  branches: [master]
  repo-allowlist: [istio]

transforms:

# istio/istio master build job(s) - postsubmit(s)
- env:
    DOCKER_HUB: us-docker.pkg.dev/istio-prow-private/istio-prow-private
    GCS_BUCKET: istio-build-private/dev
    R2_BUCKET: istio-build-private/dev
  labels:
    preset-enable-netrc: "true"
    preset-override-envoy-r2: "true"
    preset-override-deps: master-istio
  requirements: [cf-r2-istio-build-private-auth]
  job-type: [postsubmit]
  job-allowlist: [release_istio_postsubmit]

# istio/istio master no-envoy jobs - presubmit(s) and postsubmit(s)
# These don't invoke `make build` / init.sh, so they don't need R2 credentials because they don't pull envoy binaries.
- labels:
    preset-enable-netrc: "true"
    preset-override-deps: master-istio
  job-type: [presubmit, postsubmit]
  job-allowlist: [lint_istio, gencheck_istio, govulncheck_istio, bookinfo-build_istio, macbuildcheck_istio, windowsbuildcheck_istio]

# istio/istio master test jobs(s) that bring up istio / download envoy - presubmit(s) and postsubmit(s)
- labels:
    preset-enable-netrc: "true"
    preset-override-envoy-r2: "true"
    preset-override-deps: master-istio
  requirements: [cf-r2-istio-build-private-auth]
  job-type: [presubmit, postsubmit]
  job-denylist: [benchmark-report_istio_postsubmit, release_istio_postsubmit, release-notes_istio, build-base-images_istio, lint_istio, gencheck_istio, govulncheck_istio, bookinfo-build_istio, macbuildcheck_istio, windowsbuildcheck_istio]

