---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: r2-credentials
  namespace: test-pods
spec:
  backendType: gcpSecretsManager
  projectId: istio-testing
  data:
  - key: cf_r2_credentials # Secret name in GSM
    name: service-account.json
