# Plugin repository allowlist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - istio
  - istio-ecosystem
  - istio-private
  trusted_org: istio
  trusted_apps:
  - dependabot

config_updater:
  maps:
    prow/gcp/config.yaml:
      name: config
    prow/gcp/plugins.yaml:
      name: plugins
    prow/gcp/cluster/jobs/**/*.yaml:
      name: job-config
      gzip: true

plugins:
  istio:
    plugins:
    - trigger

  istio-ecosystem:
    plugins:
    - trigger

  istio-private:
    plugins:
    - trigger

  istio/test-infra:
    plugins:
    - config-updater
