#!/bin/bash

# Example usage:
#
# docker/release-docker -h docker.io/istio,gcr.io/istio-testing \
#  -c release \
#  -t $(git rev-parse --short HEAD),$(date +%Y%m%d%H%M%S),latest" \
#  -i "init,init_debug,app,app_debug,runtime,runtime_debug"

function usage() {
  echo "$0 \
    -c <bazel config to use> \
    -h <comma separated list of docker image repository> \
    -t <comma separated list of docker image tags> \
    -i <comma separated list of docker images>"
  exit 1
}


while getopts :c:h:i:t:: arg; do
  case ${arg} in
    c) BAZEL_ARGS="--config=${OPTARG}";;
    h) HUBS="${OPTARG}";;
    i) IMAGES="${OPTARG}";;
    t) TAGS="${OPTARG}";;
  esac
done

[[ -z "${HUBS}" ]] && usage
[[ -z "${TAGS}" ]] && usage
[[ -z "${IMAGES}" ]] && usage

if [[ "${HUB}" =~ ^gcr\.io ]]; then
  gcloud docker --authorize-only
fi

IFS=',' read -ra TAGS <<< "${TAGS}"
IFS=',' read -ra IMAGES <<< "${IMAGES}"
IFS=',' read -ra HUBS <<< "${IMAGES}"

set -ex

for IMAGE in "${IMAGES[@]}"; do
  bazel ${BAZEL_STARTUP_ARGS} run ${BAZEL_ARGS} "//docker:${IMAGE}" istio/docker:"${IMAGE}"
  for TAG in "${TAGS[@]}"; do
    for HUB in "${HUBS[@]}"; do
      docker tag istio/docker:"${IMAGE}" "${HUB}/${IMAGE}:${TAG}"
      docker push "${HUB}/${IMAGE}:${TAG}"
    done
  done
done
