apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-rotator
  namespace: cloudflare-secret-rotation
  annotations:
    iam.gke.io/gcp-service-account: cloudflare-rotator@istio-testing.iam.gserviceaccount.com
