org: istio
repo: bots
image: registry.istio.io/testing/build-tools:master-f885db5898b47d278fab4925b0f5c1d8db9d8195

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: deploy-policybot
    cluster: test-infra-trusted
    excluded_requirements: [cache]
    node_selector:
      prod: prow
    service_account_name: prowjob-bots-deployer
    regex: '^policybot/'
    types: [postsubmit]
    command:
    - entrypoint
    - make
    - -C
    - policybot
    - deploy
    requirements: [docker]
