org: istio
repo: bots
image: 678412441677.dkr.ecr.us-west-2.amazonaws.com/ghcr/istio/testing/build-tools:master-3d06fb2820260b49713de5d906e085598facaa43

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: deploy-policybot
    cluster: test-infra-trusted
    excluded_requirements: [cache]
    node_selector:
      prod: prow
    service_account_name: prowjob-bots-deployer
    regex: '^policybot/'
    types: [postsubmit]
    command:
    - entrypoint
    - make
    - -C
    - policybot
    - deploy
    requirements: [docker]
