org: istio
repo: community
image: 678412441677.dkr.ecr.us-west-2.amazonaws.com/ghcr/istio/testing/build-tools:master-3d06fb2820260b49713de5d906e085598facaa43

jobs:
  - name: lint
    command: [prow/community-lint.sh]

  - name: test
    command: [make, test]

  - name: sync-org
    types: [postsubmit]
    command: [org-gen, --write-to-github, --github-token=/etc/github-token/oauth]
    node_selector:
      prod: prow
    requirements: [github-organization]
    excluded_requirements: [cache]
    timeout: 4h
    cluster: test-infra-trusted
