org: istio
repo: enhancements
branches: [master]
support_release_branching: true
image: 678412441677.dkr.ecr.us-west-2.amazonaws.com/ghcr/istio/testing/build-tools:master-3d06fb2820260b49713de5d906e085598facaa43
jobs:
- name: validate-features
  types: [presubmit]
  modifiers: [presubmit_optional]
  command:
    - ../test-infra/scripts/validate_schema.sh
    - --document-path=./features.yaml
    - --schema-path=./features_schema.json
  repos: [istio/test-infra@master,istio/tools@master]
