org: istio
repo: enhancements
branches: [master]
support_release_branching: true
image: registry.istio.io/testing/build-tools:master-f885db5898b47d278fab4925b0f5c1d8db9d8195
jobs:
- name: validate-features
  types: [presubmit]
  modifiers: [presubmit_optional]
  command:
    - ../test-infra/scripts/validate_schema.sh
    - --document-path=./features.yaml
    - --schema-path=./features_schema.json
  repos: [istio/test-infra@master,istio/tools@master]
