org: istio
repo: enhancements
branches: [master]
support_release_branching: true
image: registry.istio.io/testing/build-tools:master-7f5d77ade26da4b04ed42f353d9c26fbb3a4e7f1
jobs:
- name: validate-features
  types: [presubmit]
  modifiers: [presubmit_optional]
  command:
    - ../test-infra/scripts/validate_schema.sh
    - --document-path=./features.yaml
    - --schema-path=./features_schema.json
  repos: [istio/test-infra@master,istio/tools@master]
