org: istio
repo: proxy
support_release_branching: true
image: registry.istio.io/testing/build-tools-proxy:master-344978549023107b14c57d2ef8523d41b82ccc76
node_selector:
  testing: build-pool

jobs:
- name: test
  service_account_name: prowjob-default-sa
  types: [presubmit]
  command: [./prow/proxy-presubmit.sh]
  timeout: 4h
  env:
    - name: BAZEL_BUILD_RBE_INSTANCE
      value: ""
    - name: BAZEL_BUILD_RBE_CACHE
      value: http://bazel-remote.bazel-remote.svc.cluster.local:8080

- name: test-asan
  service_account_name: prowjob-default-sa
  types: [presubmit]
  command: [./prow/proxy-presubmit-asan.sh]
  timeout: 4h
  env:
    - name: BAZEL_BUILD_RBE_INSTANCE
      value: ""
    - name: BAZEL_BUILD_RBE_CACHE
      value: http://bazel-remote.bazel-remote.svc.cluster.local:8080

- name: test-arm
  architectures: [arm64]
  env:
  - name: ARCH_SUFFIX
    value: $(params.arch)
  - name: BAZEL_BUILD_RBE_INSTANCE
    value: ""
  - name: BAZEL_BUILD_RBE_CACHE
    value: http://bazel-remote.bazel-remote.svc.cluster.local:8080
  service_account_name: prowjob-default-sa
  types: [presubmit]
  command: [./prow/proxy-presubmit.sh]
  timeout: 6h
  # TODO: get build-pool for arm
  resources: arm
  node_selector:
    testing: test-pool

- name: release-test
  service_account_name: prowjob-default-sa
  types: [presubmit]
  command: [./prow/proxy-presubmit-release.sh]
  timeout: 6h
  env:
    - name: BAZEL_BUILD_RBE_INSTANCE
      value: ""
    - name: BAZEL_BUILD_RBE_CACHE
      value: http://bazel-remote.bazel-remote.svc.cluster.local:8080

- name: release-test
  architectures: [arm64]
  env:
  - name: ARCH_SUFFIX
    value: $(params.arch)
  - name: BUILD_ENVOY_BINARY_ONLY
    value: "1"
  - name: BAZEL_BUILD_RBE_INSTANCE
    value: ""
  - name: BAZEL_BUILD_RBE_CACHE
    value: http://bazel-remote.bazel-remote.svc.cluster.local:8080
  service_account_name: prowjob-default-sa
  types: [presubmit]
  command: [./prow/proxy-presubmit-release.sh]
  timeout: 6h
  # TODO: get build-pool for arm
  resources: arm
  node_selector:
    testing: test-pool

- name: release
  service_account_name: prowjob-testing-write
  types: [postsubmit]
  command: [entrypoint, ./prow/proxy-postsubmit.sh]
  requirements: [docker, cf-r2-istio-build-auth]
  timeout: 6h
  env:
  - name: BAZEL_BUILD_RBE_INSTANCE
    value: ""
  - name: BAZEL_BUILD_RBE_CACHE
    value: http://bazel-remote.bazel-remote.svc.cluster.local:8080
- name: release
  architectures: [arm64]
  env:
  - name: ARCH_SUFFIX
    value: $(params.arch)
  - name: BUILD_ENVOY_BINARY_ONLY
    value: "1"
  - name: BAZEL_BUILD_RBE_INSTANCE
    value: ""
  - name: BAZEL_BUILD_RBE_CACHE
    value: http://bazel-remote.bazel-remote.svc.cluster.local:8080
  service_account_name: prowjob-testing-write
  types: [postsubmit]
  command: [entrypoint, ./prow/proxy-postsubmit.sh]
  requirements: [docker, cf-r2-istio-build-auth]
  timeout: 6h
  # TODO: get build-pool for arm
  resources: arm
  node_selector:
    testing: test-pool

- name: update-istio
  types: [postsubmit]
  command:
  - entrypoint
  - ../test-infra/tools/automator/automator.sh
  - --org=$AUTOMATOR_ORG
  - --repo=istio
  - "--title=Automator: update proxy@$AUTOMATOR_SRC_BRANCH in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
  - --labels=auto-merge,release-notes-none
  - --modifier=update_proxy_dep
  - --token-env
  - --git-exclude=^common/
  - --cmd=bin/update_proxy.sh $AUTOMATOR_SHA
  requirements: [github-istio-testing]
  repos: [istio/test-infra@master]
  image: registry.istio.io/testing/build-tools:master-86f324b68d67e04114aeb5cac5de028bfb58bf5b
  env:
    - name: AUTOMATOR_ORG
      value: istio
  timeout: 4h

- name: update-proxy
  types: [periodic]
  interval: 24h
  command:
  - entrypoint
  - ../test-infra/tools/automator/automator.sh
  - --org=$AUTOMATOR_ORG
  - --repo=proxy
  - "--title=Automator: update envoy@$AUTOMATOR_SRC_BRANCH in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
  - --labels=auto-merge
  - --modifier=update_envoy_dep
  - --token-env
  - --cmd=UPDATE_BRANCH=main scripts/update_envoy.sh
  requirements: [github-istio-testing]
  repos: [istio/test-infra@master]
  image: registry.istio.io/testing/build-tools:master-86f324b68d67e04114aeb5cac5de028bfb58bf5b
  env:
    - name: AUTOMATOR_ORG
      value: istio
  timeout: 4h

- name: update-go-control-plane
  types: [periodic]
  cron: "0 2 * * 0" # run each Sunday at 02:00AM UTC
  command:
  - entrypoint
  - ../test-infra/tools/automator/automator.sh
  - --org=$AUTOMATOR_ORG
  - --repo=proxy
  - "--title=Automator: update go-control-plane in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
  - --labels=auto-merge,release-notes-none
  - --modifier=update_deps
  - --token-env
  - --cmd=go get github.com/envoyproxy/go-control-plane/contrib@main github.com/envoyproxy/go-control-plane/envoy@main && go mod tidy
  disable_release_branching: true
  requirements: [github-istio-testing]
  repos: [istio/test-infra@master]
  image: registry.istio.io/testing/build-tools:master-86f324b68d67e04114aeb5cac5de028bfb58bf5b
  env:
    - name: AUTOMATOR_ORG
      value: istio

resources_presets:
  default:
    requests:
      memory: "100G"
      cpu: "30"
    limits:
      memory: "240G"
      cpu: "64"
  # Currently our ARM nodes are tiny while we try to get more capacity
  arm:
    requests:
      memory: "16G"
      cpu: "4"
