#!/bin/bash

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1090
. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

CMAKE_VERSION='3.8.0'
CMAKE_BASE_URL="https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}"
CMAKE_ARCHIVE="cmake-${CMAKE_VERSION}-Linux-x86_64"
CMAKE_URL="${CMAKE_BASE_URL}/${CMAKE_ARCHIVE}.tar.gz"
CMAKE_DOWNLOAD_DIRECTORY="${TOOLS_DIR}/cmake"
CMAKE_DIRECTORY="/usr/local/cmake"

function install_cmake() {
  mkdir -p "${CMAKE_DOWNLOAD_DIRECTORY}"
  retry -n 3 wget -q -nc -P "${CMAKE_DOWNLOAD_DIRECTORY}" "${CMAKE_URL}" \
      || error_exit 'Could not download cmake.'
  ${SUDO} mkdir -p "${CMAKE_DIRECTORY}"
  ${SUDO} tar -C ${CMAKE_DIRECTORY} -xzf "${CMAKE_DOWNLOAD_DIRECTORY}/${CMAKE_ARCHIVE}.tar.gz" \
      || error_exit 'Could not unpack cmake.'

  ${SUDO} mv ${CMAKE_DIRECTORY}/${CMAKE_ARCHIVE}/* ${CMAKE_DIRECTORY}/
  ${SUDO} rmdir ${CMAKE_DIRECTORY}/${CMAKE_ARCHIVE}/

  ${SUDO} ln -s -f ${CMAKE_DIRECTORY}/bin/cmake /usr/local/bin
  echo 'CMAKE intalled.'
}
