#!/bin/bash

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

NINJA_VERSION='1.9.0'
NINJA_BASE_URL="https://github.com/ninja-build/ninja/releases/download/v${NINJA_VERSION}"
NINJA_ARCHIVE="ninja-linux"
NINJA_URL="${NINJA_BASE_URL}/${NINJA_ARCHIVE}.zip"
NINJA_DOWNLOAD_DIRECTORY="${TOOLS_DIR}/ninja"
NINJA_DIRECTORY="/usr/local/ninja"

function install_ninja() {
  if [[ ! -d "${NINJA_DIRECTORY}" ]]; then
    ${SUDO} mkdir -p "${NINJA_DIRECTORY}"
  fi
  if [[ ! -d "${NINJA_DOWNLOAD_DIRECTORY}" ]]; then
    mkdir -p "${NINJA_DOWNLOAD_DIRECTORY}"
  fi
  
  retry -n 3 wget -q -nc -P "${NINJA_DOWNLOAD_DIRECTORY}" "${NINJA_URL}" \
      || error_exit 'Could not download ninja.'
  ${SUDO} unzip "${NINJA_DOWNLOAD_DIRECTORY}/${NINJA_ARCHIVE}.zip" -d ${NINJA_DIRECTORY}  \
      || error_exit 'Could not unpack ninja.'

  ${SUDO} ln -s -f ${NINJA_DIRECTORY}/ninja /usr/local/bin
  echo 'NINJA intalled.'
}
