#!/bin/bash

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

GO_VERSION='1.8'
GO_BASE_URL="https://storage.googleapis.com/golang"
GO_ARCHIVE="go${GO_VERSION}.linux-amd64.tar.gz"
GO_URL="${GO_BASE_URL}/${GO_ARCHIVE}"
GO_DIRECTORY="${TOOLS_DIR}/go"

export GOPATH=/opt/go
mkdir -p ${GOPATH}/bin

function install_go_pkg() {
  go get github.com/github/hub
}

function update_go() {
  local go_current="$(go version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')" \
    || go_current='none'

  if [[ -d "${GO_DIRECTORY}" ]]; then
    mkdir -p "${GO_DIRECTORY}"
  fi

  if [[ "${GO_VERSION}" != "${go_current}" ]]; then
    retry -n 3 wget -q -nc -P "${GO_DIRECTORY}" "${GO_URL}" \
      || error_exit 'Could not download go.'
    ${SUDO} tar -C /usr/local -xzf "${GO_DIRECTORY}/${GO_ARCHIVE}" \
      || error_exit 'Could not install go.'
    export PATH=${PATH}:/usr/local/go/bin
  fi
  install_go_pkg
  echo 'Go up-to-date.'
}

