#!/bin/bash

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

# Use Bazelisk launcher for Bazel (automatically downloads required version of Bazel).
BAZELISK_VERSION="v1.0"
BAZELISK_BASE_URL="https://github.com/bazelbuild/bazelisk/releases/download"
BAZELISK_BIN="bazelisk-linux-amd64"
BAZELISK_URL="${BAZELISK_BASE_URL}/${BAZELISK_VERSION}/${BAZELISK_BIN}"
BAZELISK_DIRECTORY="${TOOLS_DIR}/bazelisk"

function update_bazel() {
  local bazel_current="$(bazel version | grep -oh 'Bazelisk version: v[0-9]*\.[0-9]*')" \
    || bazel_current='none'

  if [[ -d "${BAZELISK_DIRECTORY}" ]]; then
    mkdir -p "${BAZELISK_DIRECTORY}"
  fi

  if [[ "${BAZELISK_VERSION}" != "${bazel_current}" ]]; then
    retry -n 3 wget -q -nc -P "${BAZELISK_DIRECTORY}" "${BAZELISK_URL}" \
      || error_exit "Could not download bazelisk"
    ${SUDO} chmod +x "${BAZELISK_DIRECTORY}/${BAZELISK_BIN}" \
      || error_exit "Could not mark bazelisk binary as executable"
    ${SUDO} mv "${BAZELISK_DIRECTORY}/${BAZELISK_BIN}" "/usr/local/bin/bazel" \
      || error_exit "Could not install bazelisk"
    set_bazel
    ${SUDO} ${BAZEL} shutdown
    ${SUDO} rm -rf ${HOME}/.cache/bazel
    ${SUDO} rm -rf ${HOME}/.cache/bazelisk
  fi
  echo 'Bazelisk up-to-date.'
}
