#!/bin/bash
# May require sudo login.

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

# EE
#Version: 1.13.1-0~ubuntu-xenial
#DOCKER_VERSION='1.13.1'
# CE
#Version: 17.05.0~ce-0~ubuntu-xenial
DOCKER_VERSION=17.05.0

# Ubuntu 16-04
XENIAL_REPO='ubuntu-xenial'
# EE
#XENIAL_VERSION_SUFFIX="-0~${XENIAL_REPO}"
# CE
XENIAL_VERSION_SUFFIX="~ce-0~${XENIAL_REPO}"
# Default
REPO="${XENIAL_REPO}"
VERSION_SUFFIX="${XENIAL_VERSION_SUFFIX}"

function set_platform_env() {
  local platform="${1}"
  case "${platform}" in
    'ubuntu-16-04')
      REPO="${XENIAL_REPO}"
      VERSION_SUFFIX="${XENIAL_VERSION_SUFFIX}";;
    *) error_exit "Plaform ${platform} is not supported."
  esac
}

function purge_docker() {
  echo 'Removing older docker installation if any'
  ${SUDO} apt-get purge -y docker.io* \
    || echo 'docker.io not installed, proceeding...'
}

function install_docker() {
  echo 'Installing docker'
  ${SUDO} apt-key adv \
    --keyserver hkp://ha.pool.sks-keyservers.net:80 \
    --recv-keys 58118E89F3A912897C070ADBF76221572C52609D \
  && clear_apt \
  && ${SUDO} apt-get -qqy install docker-engine="${DOCKER_VERSION}${VERSION_SUFFIX}" \
  && return 0
  return 1
}

function update_apt() {
  echo 'Adding repo for docker'
  echo "deb https://apt.dockerproject.org/repo ${REPO} main" \
    | ${SUDO} tee /etc/apt/sources.list.d/docker.list
}

function update_docker() {
  local version="$(docker --version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')"
  if [[ "${version}" != "${DOCKER_VERSION}" ]]; then
    local platform="${1}"
    set_platform_env "${platform}"
    update_apt
    retry install_docker || error_exit 'Cannot install docker.'
  fi
  echo 'Docker is up to date.'
}
