#!/bin/bash
# May require sudo login.

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

LLVM_VERSION=7

# Ubuntu 16-04
LLVM_REPO='xenial'

function install_clang() {
  echo 'Installing clang'
  curl https://apt.llvm.org/llvm-snapshot.gpg.key | ${SUDO} apt-key add - \
  && clear_apt \
  && ${SUDO} apt-get -qqy install "clang-${LLVM_VERSION}" "clang-format-${LLVM_VERSION} clang-tidy-${LLVM_VERSION} lld-${LLVM_VERSION} libc++-${LLVM_VERSION}-dev libc++abi-${LLVM_VERSION}-dev" \
  && return 0
  return 1
}

function update_llvm_apt() {
  echo 'Adding repo for llvm'
  echo "deb http://apt.llvm.org/${LLVM_REPO}/ llvm-toolchain-${LLVM_REPO}-${LLVM_VERSION} main" \
    | ${SUDO} tee /etc/apt/sources.list.d/llvm.list
}

function update_clang() {
  if [[ ! -x "$(command -v clang-${LLVM_VERSION})" ]]; then
    update_llvm_apt
    retry install_clang || error_exit 'Cannot install clang.'
  fi
  echo 'clang is up to date.'
}
