#!/bin/bash

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

WRK_VERSION='4.0.2'
WRK_BASE_URL="https://storage.googleapis.com/istio-tools/wrk"
WRK_BINARY="wrk-${WRK_VERSION}"
WRK_URL="${WRK_BASE_URL}/${WRK_BINARY}"
WRK_DIRECTORY="${TOOLS_DIR}/wrk"

function update_wrk() {
  local wrk_current="$(wrk --version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')" \
    || wrk_current='none'

  if [[ -d "${WRK_DIRECTORY}" ]]; then
    mkdir -p "${WRK_DIRECTORY}"
  fi

  if [[ "${WRK_VERSION}" != "${wrk_current}" ]]; then
    retry -n 3 wget -q -nc -P "${WRK_DIRECTORY}" "${WRK_URL}" \
      || error_exit 'Could not download wrk.'
    ${SUDO} cp -f "${WRK_DIRECTORY}/${WRK_BINARY}" /usr/local/bin/wrk \
      || error_exit 'Could not install wrk.'
    ${SUDO} chmod +x /usr/local/bin/wrk \
      || error_exit 'Could not change permission on wrk'
    export PATH=${PATH}:/usr/local/bin
  fi
  echo 'Go up-to-date.'
}

