#!/bin/bash

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

HELM_VERSION='v2.7.2'
HELM_BASE_URL="https://storage.googleapis.com/kubernetes-helm"
HELM_ARCHIVE="helm-${HELM_VERSION}-linux-amd64.tar.gz"
HELM_URL="${HELM_BASE_URL}/${HELM_ARCHIVE}"

# Install helm cli
function install_helm_cli() {
    cd /tmp
    curl -Lo /tmp/helm.tgz ${HELM_URL}
    tar xfz helm.tgz
    mv linux-amd64/helm /usr/local/bin
    rm -rf helm.tgz linux-amd64
}

function update_helm() {
  install_helm_cli
  echo 'Helm up-to-date.'
}
