#!/bin/bash
# May require sudo login.

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1090
. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

#Version: 18.06.1~ce-0~ubuntu-xenial
DOCKER_VERSION=18.06.1

# Ubuntu 16-04
XENIAL_REPO='ubuntu'
# EE
#XENIAL_VERSION_SUFFIX="-0~${XENIAL_REPO}"
# CE
XENIAL_VERSION_SUFFIX="~ce~3-0~${XENIAL_REPO}"
# Default
VERSION_SUFFIX="${XENIAL_VERSION_SUFFIX}"

function set_platform_env() {
  local platform="${1}"
  case "${platform}" in
    'ubuntu-16-04')
      VERSION_SUFFIX="${XENIAL_VERSION_SUFFIX}";;
    *) error_exit "Plaform ${platform} is not supported."
  esac
}

function purge_docker() {
  echo 'Removing older docker installation if any'
  ${SUDO} apt-get purge -y docker.io* docker-engine docker\
    || echo 'docker.io not installed, proceeding...'
}

function install_docker() {
  echo 'Installing docker'
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | ${SUDO} apt-key add - \
  && clear_apt \
  && ${SUDO} apt-get -qqy install docker-ce="${DOCKER_VERSION}${VERSION_SUFFIX}" \
  && return 0
  return 1
}

function update_apt() {
  echo 'Adding repo for docker'
  sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
}

function update_docker() {
  # shellcheck disable=SC2155
  local version="$(docker --version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')"
  if [[ "${version}" != "${DOCKER_VERSION}" ]]; then
    local platform="${1}"
    set_platform_env "${platform}"
    update_apt
    retry install_docker || error_exit 'Cannot install docker.'
  fi
  echo 'Docker is up to date.'
}
