apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gcsweb
  namespace: gcs
spec:
  # Just explicitly set the LB healthcheck path to not have to deal with
  # back inferences (e.g. defaults to /)
  healthCheck:
    type: HTTP
    requestPath: /robots.txt
