#!/bin/bash

REMOTE_WORKER='bazel-bin/src/tools/remote_worker/remote_worker'
REMOTE_CACHE='bazel-bin/src/tools/remote_worker/remote_cache'
HAZELCAST_JAR='third_party/hazelcast/hazelcast-3.6.4.jar'

BAZEL_CHECKOUT='/tmp/bazel'
CACHE_PORT=8080
HAZELCAST_PORT=5701
WORKER_PORT=8081
WORK_PATH='/tmp/test'

cd "${BAZEL_CHECKOUT}"

while getopts chw arg; do
  case ${arg} in
    c)
      "${REMOTE_CACHE}" --listen_port="${CACHE_PORT}"
      ;;
    h)
      java -cp "${HAZELCAST_JAR}" com.hazelcast.core.server.StartServer
      ;;
    w)
      rm -rf "${WORK_PATH}"
      "${REMOTE_WORKER}" --work_path="${WORK_PATH}" \
        --listen_port="${WORKER_PORT}"
      ;;
    *) echo "Invalid option: -${OPTARG}";;
  esac
done

