#!/bin/bash

# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ ${UID} -ne 0 ]]; then
  SUDO=sudo
fi
${SUDO} service docker start

if ! [[ "${@}" =~ "-tunnel " ]]; then
  if [[ -n "${JENKINS_TUNNEL}" ]]; then
    TUNNEL="-tunnel ${JENKINS_TUNNEL}"
  fi
fi

if [[ -n "${JENKINS_URL}" ]]; then
  URL="-url ${JENKINS_URL}"
fi

if [ -z "${JNLP_PROTOCOL_OPTS}" ]; then
  echo "Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior"
  JNLP_PROTOCOL_OPTS="-Dorg.jenkinsci.remoting.engine.JnlpProtocol3.disabled=true"
fi

java ${JAVA_OPTS} ${JNLP_PROTOCOL_OPTS} \
  -cp /usr/share/jenkins/slave.jar hudson.remoting.jnlp.Main \
  -headless ${TUNNEL} ${URL} "${@}"
