#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ESP_ROOT="$(cd "${DIR}/../.." && pwd)"

. "${ESP_ROOT}"/scripts/all-utilities || { echo "Cannot load utilities" ; exit 1 ; }

echo 'Verifying Docker Install'
docker info || error_exit 'Docker is not installed properly'
docker version || error_exit 'Docker is not installed properly'
docker run hello-world || error_exit 'Docker is not installed properly'

echo 'Verifying Bazel installation'
bazel version || error_exit 'Bazel is not installed properly'

echo 'Verifying gcloud installation'
gcloud version || error_exit 'gcloud is not installed properly'

echo 'Verifying kubectl installation'
kubectl version || error_exit 'kubectl is not installed properly'

echo 'Verifying gsutil installation'
gsutil version || error_exit 'gsutil is not installed properly'

echo 'Verifying that the user is jenkins'
THIS_USER="$(whoami)"
[[ "${THIS_USER}" == 'jenkins' ]] || error_exit 'Slaves should be running as jenkins user'
