#!/bin/bash

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIR="${ROOT}/scripts"

. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
export DEBIAN_FRONTEND=noninteractive

NAMESPACE='jenkins'
APP='master'
BUCKET='gs://istio-tools/jenkins-secrets'

BACKUP_HOME='''BACKUP_FILES="$(find /var/jenkins_home \
  \( -not -path "/var/jenkins_home/*/*" -and \
     -wholename "/var/jenkins_home/*.xml" \) -o \
  \( -wholename "/var/jenkins_home/jobs/*/config.xml" \
     -and -not -regex ".*workspace@.*" \) -o \
  -wholename "/var/jenkins_home/plugins/*.jpi")"

tar czf - ${BACKUP_FILES}'''

BACKUP_SECRETS='''BACKUP_FILES="$(find /var/jenkins_home \
  -wholename "/var/jenkins_home/secrets/*")"

tar czf - ${BACKUP_FILES}'''

GIT_FILES="$(git status -s)"
[[ -z "${GIT_FILES}" ]] \
  || error_exit "You have modified files. Please commit or reset your workspace."

rm -rf jenkins_home/*

POD_NAME="$(kubectl get pods \
  --selector=app="${APP}" \
  -n "${NAMESPACE}" \
  -o jsonpath='{.items[*].metadata.name}')"

echo "Getting backup data from pod ${POD_NAME} in ns ${NAMESPACE}"

kubectl exec "${POD_NAME}" -n "${NAMESPACE}" -- /bin/bash -c "${BACKUP_HOME}" \
  | tar zxvf - --strip-components 2 -C "${ROOT}/jenkins_home"

git add .
git commit -m "Backup Jenkins Home"

COMMIT="$(git rev-parse --verify HEAD)"
ARCHIVE="${BUCKET}/secrets-${COMMIT}.tar.gz"

kubectl exec "${POD_NAME}" -n "${NAMESPACE}" -- /bin/bash -c "${BACKUP_SECRETS}" \
  | gsutil cp - "${ARCHIVE}"
