#!/bin/bash

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIR="${ROOT}/scripts"

. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
export DEBIAN_FRONTEND=noninteractive

ARGS=()
CLUSTER_NAME='e2e-testing'
PROJECT_ID='istio-testing'
ZONE='us-west1-a'
HOURS_OLD=2

PROTECTED_NS='default,kube-public,kube-system'
ROLE_STARTSWITH='istio-'

while getopts :c:h:p:z: arg; do
  case ${arg} in
    c) CLUSTER_NAME="${OPTARG}";;
    h) HOURS_OLD=${OPTARG};;
    p) PROJECT_ID="${OPTARG}";;
    z) ZONE="${OPTARG}";;
    *) error_exit "Unrecognized argument -${OPTARG}";;
  esac
done

[[ -n "${PROJECT_ID}" ]] && ARGS+=(--project "${PROJECT_ID}")
[[ -n "${ZONE}" ]] && ARGS+=(--zone "${ZONE}")

if [[ ${CLUSTER_NAME} != '' ]]; then
  echo 'Getting credentials for Kubernetes cluster'
  gcloud container clusters get-credentials ${CLUSTER_NAME} ${ARGS[@]}\
    || error_exit 'Could not get kubectl config for cluster'
fi

NS_JSON="$(mktemp /tmp/cluster.cleanup.XXXXX.json)"
ROLE_JSON="$(mktemp /tmp/cluster.cleanup.XXXXX.json)"

kubectl get ns -o json > "${NS_JSON}"
kubectl get clusterrolebindings -o json > "${ROLE_JSON}"

function filter_items() {
python - <<EOF ${1} ${2} ${3} ${4}

import sys
import datetime
import json

json_file = sys.argv[1]
hours_old = int(sys.argv[2])
filters = str(sys.argv[3]).strip().split(',')
startswith = str(sys.argv[4]).strip().split(',')

with open(json_file, 'r') as f:
  result = json.load(f)

items = {}

date_format = '%Y-%m-%dT%H:%M:%SZ'

for i in result['items']:
  item = i['metadata']['name']
  ts = i['metadata']['creationTimestamp']
  skip = False

  for f in filters:
    if item.startswith(f):
      skip = True
      break

  for s in startswith:
    if not item.startswith(s):
      skip = True
      break

  if not skip:
    items[item] = datetime.datetime.strptime(ts, date_format)

min_time = datetime.datetime.utcnow() - datetime.timedelta(hours=hours_old)

for k, v in items.iteritems():
  if v < min_time: print k
EOF

}

NAMESPACES=$(filter_items "${NS_JSON}" ${HOURS_OLD} "${PROTECTED_NS}" "''")
ROLES=$(filter_items "${ROLE_JSON}" ${HOURS_OLD} "''" "${ROLE_STARTSWITH}")

if [[ -n "${NAMESPACES}" ]]; then
  echo "${NAMESPACES}" | xargs kubectl delete ns
fi

if [[ -n "${ROLES}" ]]; then
  echo "${ROLES}" | xargs kubectl delete clusterrolebindings
fi


