#!/bin/bash

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

declare -A G_TO_V

G_TO_V['com_github_beorn7_perks']='github.com/beorn7/perks'
G_TO_V['com_github_golang_protobuf']='github.com/golang/protobuf'
G_TO_V['com_github_googleapis_gax_go']='github.com/googleapis/gax-go'
G_TO_V['com_github_google_go_github']='github.com/google/go-github'
G_TO_V['com_github_google_go_querystring']='github.com/google/go-querystring'
G_TO_V['com_github_hashicorp_errwrap']='github.com/hashicorp/errwrap'
G_TO_V['com_github_hashicorp_go_multierror']='github.com/hashicorp/go-multierror'
G_TO_V['com_github_matttproud_golang_protobuf_extensions']='github.com/matttproud/golang_protobuf_extensions'
G_TO_V['com_github_prometheus_client_golang']='github.com/prometheus/client_golang'
G_TO_V['com_github_prometheus_client_model']='github.com/prometheus/client_model'
G_TO_V['com_github_prometheus_common']='github.com/prometheus/common'
G_TO_V['com_github_prometheus_procfs']='github.com/prometheus/procfs'
G_TO_V['com_google_cloud_go']='cloud.google.com/go'
G_TO_V['org_golang_google_api']='google.golang.org/api'
G_TO_V['org_golang_google_appengine']='google.golang.org/appengine'
G_TO_V['org_golang_google_genproto']='google.golang.org/genproto'
G_TO_V['org_golang_google_grpc']='google.golang.org/grpc'
G_TO_V['org_golang_x_net']='golang.org/x/net'
G_TO_V['org_golang_x_oauth2']='golang.org/x/oauth2'
G_TO_V['org_golang_x_tools']='golang.org/x/tools'

for key in ${!G_TO_V[@]}; do
  value="${G_TO_V["${key}"]}"
  find ${ROOT} -type f -name BUILD.bazel -exec sed -i  "s,@${key}//,//vendor/${value}/,g" {} \;
done

find ${ROOT} -type f -name BUILD.bazel -exec sed -i  "s,\(//vendor/.*\)/:,\1:,g" {} \;

${ROOT}/scripts/fmt.sh
