#!/bin/bash
# May require sudo login.

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1090
. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
# TOOLS
# shellcheck disable=SC1090
. "${DIR}"/tools/linux-install-bazel || error_exit "Cannot load Bazel install script"
# shellcheck disable=SC1090
. "${DIR}"/tools/linux-install-clang || error_exit "Cannot load Clang install script"
# shellcheck disable=SC1090
. "${DIR}"/tools/linux-install-cmake || error_exit "Cannot load cmake install script"
# shellcheck disable=SC1090
. "${DIR}"/tools/linux-install-docker || error_exit "Cannot load Docker install script"
# shellcheck disable=SC1090
. "${DIR}"/tools/linux-install-gcloud || error_exit "Cannot load gcloud install script"
# shellcheck disable=SC1090
. "${DIR}"/tools/linux-install-golang || error_exit "Cannot load golang install script"
# shellcheck disable=SC1090
. "${DIR}"/tools/linux-install-ninja || error_exit "Cannot load ninja install script"
# shellcheck disable=SC1090
. "${DIR}"/tools/linux-install-repo || error_exit "Cannot load repo install script"
# shellcheck disable=SC1090
. "${DIR}"/tools/linux-install-wrk || error_exit "Cannot load wrk install script"
# shellcheck disable=SC1090
. "${DIR}"/tools/linux-install-protoc || error_exit "Cannot load protoc install script"
# shellcheck disable=SC1090
. "${DIR}"/tools/linux-install-helm || error_exit "Cannot load helm install script"
# shellcheck disable=SC1090
. "${DIR}"/tools/linux-install-gcc || error_exit "Cannot load gcc install script"

export DEBIAN_FRONTEND=noninteractive

function install_packages() {
  echo "Installing tools."
  clear_apt \
  && ${SUDO} apt-get -qqy install \
    automake \
    autotools-dev \
    apt-transport-https \
    build-essential \
    ca-certificates \
    curl \
    g++ \
    libtool \
    lsb-release \
    m4 \
    openjdk-8-jdk-headless \
    pkg-config \
    python \
    python-yaml \
    realpath \
    ruby \
    rubygems \
    ruby-dev \
    software-properties-common \
    time \
    unzip \
    uuid-dev \
    uuid-runtime \
    wget \
    zip \
    zlib1g-dev \
    && gem install --no-ri --no-rdoc fpm \
    && return 0
  return 1
}


while getopts :b:p: arg; do
  # shellcheck disable=SC2220
  # shellcheck disable=SC2034
  case ${arg} in
    p) PLATFORM="${OPTARG}";;
    b) TOOLS_BUCKET="${OPTARG}";;
  esac
done

[[ -z "${PLATFORM}" ]] && error_exit 'PLATFORM is not set'

echo 'Clearing packages in apt'
${SUDO} apt-get clean

# Installing dependencies
retry install_packages || error_exit 'Cannot install required packages.'

# Installing tools
echo "Installing tools if necessary"
if [[ -d "${TOOLS_DIR}" ]]; then
  [[ -n "${SUDO}" ]] && ${SUDO} chown -R "${USER}" "${TOOLS_DIR}"
else
  # shellcheck disable=SC2174
  mkdir -p "${TOOLS_DIR}" -m 0777
fi
update_docker "${PLATFORM}"
update_protoc
update_gcloud
update_go
update_repo
update_wrk
update_bazel
update_clang
update_helm
update_gcc
install_cmake
install_ninja
clear_apt

echo "Software installation complete."
