defaults:
  branches:
  - release-1.31
  repo-allowlist:
  - istio
org: istio
repo: istio
transforms:
- env:
    DOCKER_HUB: us-docker.pkg.dev/istio-prow-private/istio-prow-private
    GCS_BUCKET: istio-build-private/dev
    R2_BUCKET: istio-build-private/dev
  job-allowlist:
  - release_istio_release-1.31_postsubmit
  job-type:
  - postsubmit
  labels:
    preset-enable-netrc: "true"
    preset-override-deps: release-1.31-istio
    preset-override-envoy-r2: "true"
  requirements:
  - cf-r2-istio-build-private-auth
- job-allowlist:
  - lint_istio_release-1.31
  - gencheck_istio_release-1.31
  - govulncheck_istio_release-1.31
  - bookinfo-build_istio_release-1.31
  - macbuildcheck_istio_release-1.31
  - windowsbuildcheck_istio_release-1.31
  job-type:
  - presubmit
  - postsubmit
  labels:
    preset-enable-netrc: "true"
    preset-override-deps: release-1.31-istio
- job-denylist:
  - benchmark-report_istio_release-1.31_postsubmit
  - release_istio_release-1.31_postsubmit
  - release-notes_istio_release-1.31
  - build-base-images_istio_release-1.31
  - lint_istio_release-1.31
  - gencheck_istio_release-1.31
  - govulncheck_istio_release-1.31
  - bookinfo-build_istio_release-1.31
  - macbuildcheck_istio_release-1.31
  - windowsbuildcheck_istio_release-1.31
  job-type:
  - presubmit
  - postsubmit
  labels:
    preset-enable-netrc: "true"
    preset-override-deps: release-1.31-istio
    preset-override-envoy-r2: "true"
  requirements:
  - cf-r2-istio-build-private-auth
