# This hosts the Istio Slack invitation service.
# See https://docs.google.com/document/d/1Pf6vS5SiYuSD55atbosoSHktIi1N08p-P480buzCrDk/ for more info
# The invite link needs to be updated every 2000 uses with a new link generated by Slack support.
# (Links generated from the Slack UI only allow 400 invites.)
# TODO: improve this
resource "google_cloud_run_v2_service" "redirector" {
  location = "us-central1"
  name     = "redirector"
  project  = local.project_id
  template {
    max_instance_request_concurrency = 80
    revision                         = null
    service_account                  = "589046318233-compute@developer.gserviceaccount.com"
    session_affinity                 = false
    timeout                          = "900s"
    containers {
      # Built from https://github.com/ahmetb/serverless-url-redirect
      image = "gcr.io/istio-testing/redirector"
      env {
        name  = "REDIRECT_URL"
        # expires 2024-09-13 or after 2000 uses
        value = "https://join.slack.com/t/istio/shared_invite/zt-23hxe505s-dqKi3O~~YzYA88Qw1ITzeA" 
      }
      resources {
        cpu_idle = true
        limits = {
          cpu    = "1000m"
          memory = "256Mi"
        }
      }
    }
  }
}
